version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DB}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3307:3306'